# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MusicDiary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MusicDiary
	pod 'SwiftyGif'
	pod 'FirebaseUI'
	pod 'Alamofire', '~> 5.2'
	pod 'AlamofireImage', '~> 4.1'
	pod "SwiftyXMLParser", :git => 'https://github.com/yahoojapan/SwiftyXMLParser.git'
	pod "ScalingCarousel"
	pod 'iCarousel'
	pod 'FSCalendar'
	pod 'FirebaseFirestoreSwift'
end
